### ISSUE TITLE
Broken Sandbox - Planets Image Map

### ISSUE THREAD

**Issue by bensquire** [konvajs/site#10]
Not sure if this is a result of the image optimisations yesterday (all other images seem fine), however the following sandbox example:

http://konvajs.github.io/docs/sandbox/Planets_Image_Map.html

is missing some image resources and is not working:

http://konvajs.github.io/css/imagesshattered@2x.png
http://konvajs.github.io/css/imageslogo@2x.png

I'd submit a pull request but I'm not sure what its meant to look like.

Thanks

**Comment by lavrton** [comment]
Should work now.
