### ISSUE TITLE
Update Konva path in react-spring (react-spring/dist/konva to react-spring/konva)

### ISSUE THREAD

**Issue by ratskin** [konvajs/site#33]
On https://konvajs.github.io/docs/react/Complex_Animations.html (https://github.com/konvajs/site/blob/master/source/docs/react/Complex_Animations.md), the path to Konva for react-spring is `react-spring/dist/konva`. In the current version of react-spring (v7.2.10), it's `react-spring/konva`

**Comment by lavrton** [comment]
Fixed. Thanks for the report.
