### ISSUE TITLE
React warning (react-warning-keys) on example

### ISSUE THREAD

**Issue by GeorgeGkas** [konvajs/site#42]
The [basic example in codesandbox](https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/basic_demo?from-embed) produces a React warning. [Line 34](https://github.com/konvajs/site/blob/master/react-demos/basic_demo/src/index.js#L34) does not work as expected. On [Line 32](https://github.com/konvajs/site/blob/master/react-demos/basic_demo/src/index.js#L32) you initialize an array of length 10 with each element being `undefined`. Then call  `map` and assume that the first parameter of the callback will give you the array index, or you may assume that `...Array(10)` will give you an array of `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`, but in either case this is not how it works. The array index is passed as a second parameter in `map()` method. You need to change the code slightly like so:

```diff
- {[...Array(10)].map(i => (
+ {[...Array(10)].map((_, idx)=> (
 <Star
-  key={i}
+  key={idx}
```

This is a non critical error but prevents React from know which `<Star />` component to update. If you are using React Dev Tools you also cannot see the `<Star />` component. The above fix solves the issue.

**Comment by lavrton** [comment]
Good suggestion. Fixed. Thanks.
