### ISSUE TITLE
CodeSandboxes aren't displaying on Firefox

### ISSUE THREAD

**Issue by alexjchapman** [konvajs/site#56]
I'm using Firefox 78 on Windows, and when I view a demo page (for instance, [vuejs drag and drop](https://konvajs.org/docs/vue/Drag_And_Drop.html)) the CodeSandbox area doesn't load, so I'm just left with some text. 

This error shows in the console: 
```Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").```

I've noticed that this isn't happening on Chrome.

**Comment by lavrton** [comment]
Sometimes codesandbox is lagging. Right it now it works ok for me. Can you check it again?

**Comment by alexjchapman** [comment]
Looks like it was being blocked by Firefox's Facebook container add-on, all sorted now cheers.
