### ISSUE TITLE
Bug: rendering rich text sequence number error

### ISSUE THREAD

**Issue by linrz** [konvajs/site#70]
https://konvajs.org/docs/sandbox/Rich_Text.html

When I tested with the demo in the link above, I found that the rendered serial number was incorrect.
You can see the result in the screenshot.

![image](https://user-images.githubusercontent.com/33575974/118615145-08f2d500-b7f3-11eb-8c29-422c421a0c90.png)

**Comment by lavrton** [comment]
Closing as it is not related to Konva. It may be an issue with `html2canvas`.
