### ISSUE TITLE
Broken Code Sandbox examples in docs

### ISSUE THREAD

**Issue by denkquer** [konvajs/site#71]
I am pretty sure some update this week (yesterday?) broke countless codesandboxes on the react konva docs.

Example: https://konvajs.org/docs/react/DOM_Portal.html

Can you confirm this?

**Comment by denkquer** [comment]
did this just get fixed :O, or is codesandbox having issues

**Comment by lavrton** [comment]
codesandbox have issues from time to time. Anyway, thanks for the report.
