### ISSUE TITLE
How to limit drag of a rectangle within canvas width and height. 

### ISSUE THREAD

**Issue by silentrobi** [konvajs/site#72]
I am following this example https://codesandbox.io/s/mjw1ywlmpy . However It drags rectangle out of canvas field. I want to limit its dragging ability. Rectangle cant go outside of canvas field.

**Current behavior**
![image](https://user-images.githubusercontent.com/47764540/130367950-e3725438-fd04-40bc-9d51-22d5da256cfa.png)
**Expected Behavior**
![image](https://user-images.githubusercontent.com/47764540/130367975-b8faf863-59cf-464b-9d61-ce8446197561.png)

**Comment by lavrton** [comment]
I think this demo will give you understanding how to implement that https://konvajs.org/docs/sandbox/Limited_Drag_And_Resize.html
