### ISSUE TITLE
vue-konva zIndex functions documentation

### ISSUE THREAD

**Issue by TeyKey1** [konvajs/site#76]
Hello there.

I've been struggling a bit with the zIndex functions in vue-konva in the last couple of hours. After looking through the source and some related issues  ([#34](https://github.com/konvajs/vue-konva/issues/34) for example), it appears that functions like `moveToTop()` etc. should not be used in vue-konva and do indeed cause unexpected behavior at times as vue-konva tries to order the elements by their order in the `<template>` section. I hope that this is still correct for the current vue-konva release and not an error on my end. 

So far, I have not found a single hint about this in the official docs or in the vue-section of the Konva website (please correct me if I'm wrong). 

The same thing seems to be the case in react-konva where it is indeed documented [on the Konva website](https://konvajs.org/docs/react/zIndex.html). Basically it describes the same situation as in vue-konva, so I suggest adding a similar section to the[ vue-konva section](https://konvajs.org/docs/vue/index.html) of the website. 

If desired, I could do a pull-request for that and add it.

**Comment by lavrton** [comment]
Please make a pull request.

**Comment by TeyKey1** [comment]
Great, should have time to do that this week :blush:
